### ISSUE TITLE
height not applied to children when added dynamically

### ISSUE THREAD

**Issue by JayKandari** [joelmukuthu/angular-snapscroll#10]
If we add some child elements to "snapscroll" dynamically. those child elements do not inherit height property as their siblings carry. We need to resize window to make those newly added childs to behave like their siblings. 

Any solution for this? Thanks

BTW, awesome module :) @joelmukuthu

**Comment by joelmukuthu** [comment]
Thanks, I'm glad it's useful! :)

Hmm.. it's true that it doesn't apply the snapHeight for dynamically added children. I could add a watch function for that but that might be overkill since this is a specific edge-case. I think the "angular" way to fix this would be to call scope.$apply() when you add/remove children, since adding/removing represents an action that is external to angular and you need to let angular know of the external changes. Unfortunately that still wouldn't let snapscroll know that a new child element has been added.. I'm brainstorming here :)

Perhaps adding a watch function is the best solution for this after all. I'll check out other possible solutions for this but in the meantime you could do this hack:

``` html
<div id="snapscroll" snapscroll="" snap-height="snapHeight"></div>
```

``` javascript
// inside the controller..
angular.element('#snapscroll-id').append(childElement);
scope.snapHeight = scope.snapHeight - 1; // this results in the new element's height being set, along with other child elements
scope.snapHeight = scope.snapHeight + 1; // restore snapHeight to what it was before
```

I admit that this is quite hacky but it will get you by while I find a good solution :)

**Comment by JayKandari** [comment]
Okay, above hack seems worth, I implemented it in a very traditional ng-way. I'm using fit-window-height option.
I just did ng-repeat & pushed a new object and that's how my new content is coming. A single function is doing that for me, but after pushing new object, and then increasing & decreasing snapHeight didn't worked. 

I see you're watching snapHeight variable. However, $scope.snapHeight inside a controller is NaN. So Question. How can I access/alter value snapHeight inside any controller (or a provider)?

I too think altering snapHeight variable can solve this issue. Thanks!

**Comment by joelmukuthu** [comment]
In that case how about doing something like this:

``` html
<div snapscroll="" fit-window-height="" snap-height="snapHeight">
    <div ng-repeat="n in [1, 2, 3, 4, 5]" style="height:{{$parent.snapHeight}}px"></div>
</div>
```

Their height will be set initially by ng-repeat as it creates the elements and then after that snapscroll will update their height whenever the window is resized.

**Comment by JayKandari** [comment]
That worked like charm !! I didn't realized snap-height would solve this. This whay, snapHeight can now be accessible in controller. This is great. I'll explore more of your module @joelmukuthu  thanks.

**Comment by joelmukuthu** [comment]
No worries I'm glad it worked! Yes snapHeight has a two-way binding so changes to it should be accessible both ways. Thanks, that's appreciated
Btw I'm gonna update the demo to include this example

**Comment by JayKandari** [comment]
Glad!! it helped in understanding module better for users. :)
