### ISSUE TITLE
 showing other elements while snapscrolling - can't offset elements

### ISSUE THREAD

**Issue by evanjmg** [joelmukuthu/angular-snapscroll#11]
Hi Joel, 
I wanted to show the other elements while scrolling  (like a multiple image vertical slider). I got this to work by setting the css of the snap container to height: 100vh !important and the snap-height="282" (the size of my cards including margins) - this works nicely, especially when syncing with googlemap markers . 
 I was looking over your code and I'm not sure how to make the middle element the snapId rather than always the top element. What I would like is a container-height= "value" attribute (to avoid the height:100vh !important hack) and an snap-offset="number" which would count the number of visible snap items in the container and then always keep the snapId on that value. 
For reference, I'm doing something similar to this: http://sf.eater.com/maps/best-new-san-francisco-restaurants-heatmap-oakland-berkeley - but having multiple small cards and I'd like to have the snapID in the middle. 

Sorry if this sounds very different than the intended uses. It's an awesome directive and it works very well.  I thought  I could use it and see if works for what I wanted to do. Let me know if there's anywhere in the code where I can make this modification as I'm not very familiar scrolling in angular.

**Comment by joelmukuthu** [comment]
Hi Evan,
Sorry for the slow reply. I'm glad you're able to get some use from this and would very much like to help you set it up :). 
I'm not sure I understand your use case though.. could you paste your code here explaining what you mean by the middle element? Am I understanding right that you would like to have more than one "page" or "snap" visible at the same time?

**Comment by evanjmg** [comment]
`<div ng-if="map.markersAreReady" snap-height="282" class="vertical-cards" snapscroll=""  snap-index="map.selectedId" ng-swipe-up="map.selectedId=map.selectedId+1" ng-swipe-down="map.selectedId=map.selectedId-1" >
              <div ng-repeat="marker in map.markers | limitTo: map.markers.length track by marker.id" item-card size="thumb_" item="::marker.glp_item" selector="selectMarker(marker.id)" class="card vertical-card" alt="::marker.glp_item.name" >
              </div>
            </div>`

Above is the html nothing complex or changed. I wrote a card directive to display on top of a map. The key hack is the following css: 
`.vertical-cards {
  z-index: 10;
  position: absolute;
  top:0px;
  height:100vh !important;
  width:350px;}` and that's it. Not much to making multiple items visible. I'd like to have the snappy element offset by one, meaning one down rather than the first element.

**Comment by joelmukuthu** [comment]
Hmm.. interesting. Yes both use cases are not supported at the moment but I'm thinking of a few ways they could be solved: 
1. using a `before-snap` callback which returns an index that tells it where to scroll to. For example before it snaps to snapIndex 1, you return snapIndex+1 to always make it snap to the next element.
2. introduce scroll directives, such as `scroll-up` and `scroll-down` which work the same as the `ng-swipe-up` and `ng-swipe-down` directives, but instead for scroll events. 

But before I implement that, I think you might be able to offset the element that is snapped to by setting the snap-index to `map.selectedId+1` and adding a dummy element before the ng-repeat:

``` html
<div class="vertical-cards" ng-if="map.markersAreReady" snapscroll="" snap-height="282" snap-index="map.selectedId+1" ng-swipe...>
    <div></div> <!-- dummy element that is never scrolled to -->
    <ng-repeat...>
 </div>
</div>
```

The dummy element is there because `map.selectedId+1` will return an index that is out of bounds for the last element and snapscroll will not scroll to it.

As for the container-height issue, I think your solution is quite good considering snapscroll doesn't have support for that but option 2 above would be the best solution. You would be to separate the containers and have the parent container "send" it's scroll events to the snapscroll'd container. The combined solution could be something like this:

``` html
<div class="vertical-cards" ng-if="map.markersAreReady" scroll-up="map.selectedId=map.selectedId-1" scroll-down="map.selectedId=map.selectedId+1" ng-swipe...>
    <div snapscroll="" snap-height="282" snap-index="map.selectedId+1">
        <div></div> <!-- dummy -->
        <ng-repeat...>
    </div>
</div>
```

Could you try that and see if it works?

**Comment by joelmukuthu** [comment]
FYI #12, #13 and #14 :)

**Comment by evanjmg** [comment]
Cool. Those look interesting. With your quick fix, I get the error -> ' Expression 'map.selectedId + 1' in attribute 'snapIndex' used with directive 'snapscroll' is non-assignable'. It's at line 287  $scope.apply for the new index. I added the one there instead. It changes the index and if I have a fixed large height it does work, but it's hard to keep track of all the index changes with my particular case.  I think for now, I'll stick with leaving it up top (the client likes the position it's in now) as I have a massive angular site to build. I'll close the issue as you've addressed my problem and  opened new ones.

**Comment by evanjmg** [comment]
[#12](https://github.com/joelmukuthu/angular-snapscroll/issues/12), [#13](https://github.com/joelmukuthu/angular-snapscroll/issues/13) and [#14 ](https://github.com/joelmukuthu/angular-snapscroll/issues/14)  - I also wrote another directive in 45 lines to solve this issue - https://github.com/evanjmg/angular-track-scroll
