### ISSUE TITLE
Height set to 0px inside a ngDialog

### ISSUE THREAD

**Issue by brunomptorres** [joelmukuthu/angular-snapscroll#22]
Hi! I've been trying to use this inside a dialog (ngDialog) but the height is completely ignored, I tried setting via CSS class and inside de <div> tag as you show here and every time the dialog loads snapscroll sets it's element height to 0px. Using the fit-window-height option works like it should though. 

Any tips?

PS: Using the same code outside the dialog also works like a charm. 

PSS: Here you have a jsfiddle with the code I used: https://jsfiddle.net/brunomptorres/w08fbyq3/

**Comment by joelmukuthu** [comment]
Hi Bruno,

I've updated your fiddle to make it functional https://jsfiddle.net/w08fbyq3/1/ but I'm not able to reproduce the issue. But it sounds related to https://github.com/joelmukuthu/angular-snapscroll/issues/10 for which I added this example http://joelmukuthu.github.io/angular-snapscroll/#3. Take a look and let me know if that works :)

**Comment by joelmukuthu** [comment]
Basically the solution involves setting the children's heights at creation time, see this other fiddle https://jsfiddle.net/w08fbyq3/2/

**Comment by brunomptorres** [comment]
Hi Joel,

Maybe I could've explained it in a better way. My bad. The fiddle that you provided works perfectly and I was able to achieve the same results as you. The problem is when the container is inside a Dialog. 

I updated my fiddle to add the ngDialog, in order to reproduce the error that I mentioned.
https://jsfiddle.net/w08fbyq3/4/

As you'll see, it works outside the dialog, but after opening said dialog (using the button), it doesn't.

**Comment by joelmukuthu** [comment]
Hmm, it seems that at the time when snapscroll is applied onto the element in the template it's height is zero. I need to come up with a better way of getting the default snapHeight (https://github.com/joelmukuthu/angular-snapscroll/blob/master/src/directives/snapscroll.js#L246) but for the time being can you use the `snap-height` binding, like this https://jsfiddle.net/w08fbyq3/5/? Note that I hacked around using `$rootScope` because I didn't find a way to access `myctrl`'s scope from the template but if you know how it would be better than modifying the root scope

**Comment by brunomptorres** [comment]
With this 'hack' it works. Thanks @joelmukuthu

**Comment by joelmukuthu** [comment]
Great. Lets keep this open till I've fixed it within `snapscroll` though :)
