### ISSUE TITLE
Manual scroll in nested

### ISSUE THREAD

**Issue by jftsaraiva** [joelmukuthu/angular-snapscroll#6]
When we do a manual scroll (dragging the scrollbar) in one nested snapscroll, it reset the main snapscroll. I think it should reset the nested snapscroll.

**Comment by joelmukuthu** [comment]
Hi, I've been able to reproduce that using the [demo](http://joelmukuthu.github.io/angular-snapscroll) but I think it's happening due to a conflict with angular-swipe, where the drag on the scrollbar is interpreted as a swipe up/swipe down. It shouldn't happen in other cases I believe. Are you also using angular-swipe? Could you share the code that reproduces the bug?

**Comment by jftsaraiva** [comment]
Hi,

Sorry I haven't any code that reproduces the bug, I found that when was trying / evaluating your [demo](http://joelmukuthu.github.io/angular-snapscroll/#0).

**Comment by joelmukuthu** [comment]
Ah okay. I'll fix that in the demo by disabling swipe events on non-touch devices. But the events are localised to a single instance
